AWSTemplateFormatVersion: 2010-09-09
Description: VPC with two public Subnets.

Parameters:

  DeploymentName:
    Description: A name for this deployment
    Type: String

  Name:
    Description: Name for resources
    Type: String
    Default: example

  VpcCIDR:
    Description: CIDR range for VPC
    Type: String
    Default: 10.192.0.0/16

  Subnet1CIDR:
    Description: CIDR range for private Subnet 1
    Type: String
    Default: 10.192.20.0/24

  Subnet2CIDR:
    Description: CIDR range for private Subnet 2
    Type: String
    Default: 10.192.21.0/24

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref Name

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref Name

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Ref Name

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs  ""]
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Subnet (AZ1)

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs  ""]
      CidrBlock: !Ref Subnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Subnet (AZ2)

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC

  Subnet1:
    Description: Subnet in the 1st Availability Zone
    Value: !Ref Subnet1

  Subnet2:
    Description: Subnet in the 2nd Availability Zone
    Value: !Ref Subnet2
