AWSTemplateFormatVersion: 2010-09-09
Description: A simple S3 bucket

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref Bucket
