# Created 2021-06-23 Wed 11:05
#+TITLE:
* DeploymentName

A *deployment* is a complete deployed application, potentially comprised of many
CloudFormation stacks. This is sometimes called an "environment", but that is an
overloaded term. Use the =DeploymentName= to indicate which deployment a Stack
is part of.

#+begin_src yaml
  DeploymentName:
    Type: String
    Description: A name for this deployment
#+end_src

* KeyName

AWS does not provide a CloudFormation type for EC2 KeyPairs. This was a
deliberate choice: a KeyPair consists of a public and private key, and AWS does
not want to expose the private key in CloudFormation outputs.

This is one example where Terraform has an advantage: since Terraform runs
locally, it can create a KeyPair and save the private key locally.

So, in CloudFormation, you have two options:

1. Create the KeyPair beforehand. Then provide the =KeyName= to your
   CloudFormation template as a parameter.
2. Create the KeyPair using a CloudFormation Custom Resource (i.e. a Lambda
   Function) in your CloudFormation template. The Custom Resource must save the
   private key somewhere (like SecretsManager or SSM Parameter Store).

#+begin_src yaml
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of an EC2 KeyPair
    Default: test
#+end_src
