This document contains some common CloudFormation parameters which are included
in other documents in this project.

Parameter names should adhere to AWS [[https://aws-quickstart.github.io/naming-parms.html][parameter naming standards]].

* DeploymentName

#+begin_src yaml
  DeploymentName:
    Type: String
    Description: A name for this deployment
#+end_src

A *deployment* is a complete deployed application, potentially comprised of many
CloudFormation stacks. This is sometimes called an "environment", but that is an
overloaded term. Use the =DeploymentName= to indicate which deployment a Stack
is part of.

* KeyName

#+begin_src yaml
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The name of an EC2 KeyPair
    Default: test
#+end_src

AWS does not provide a CloudFormation type for EC2 KeyPairs. This was a
deliberate choice: a KeyPair consists of a public and private key, and AWS does
not want to expose the private key in CloudFormation outputs.

This is one example where Terraform has an advantage: since Terraform runs
locally, it can create a KeyPair and save the private key locally.

So, in CloudFormation, you have two options:

1. Create the KeyPair beforehand. Then provide the =KeyName= to your
   CloudFormation template as a parameter.
2. Create the KeyPair using a CloudFormation Custom Resource (i.e. a Lambda
   Function) in your CloudFormation template. The Custom Resource must save the
   private key somewhere (like SecretsManager or SSM Parameter Store).

* SSHCIDR

#+begin_src yaml
  SSHCIDR:
    Type: String
    Description: IP CIDR range
#+end_src

Allow SSH access from this CIDR range.
